import { Element } from 'domhandler'
import type { ChildNode } from 'domhandler'
import { slateToTemplate } from './../serializers';
import { config as defaultTemplateConfig } from './../config/default';
import { Config as SlateToTemplateConfig } from './../config/types';
import { payloadSlateToTemplateConfig } from './../template';

describe('Template conversion', () => {
  test('convert domhandler element to Template', async () => {
    const slate = [
      {
        children: [
          {
            text: 'Paragraph',
          },
        ],
        type: 'p',
      },
    ];

    const tree = slateToTemplate(slate);
    expect(tree).toMatchInlineSnapshot(`
      [
        "<p>Paragraph</p>",
      ]
    `);
  });

  it('can handle inline code tags', () => {
    const slate = [
      {
        type: 'p',
        children: [
          {
            text: 'This is editable ',
          },
          {
            text: 'rich',
            bold: true,
          },
          {
            text: ' text, ',
          },
          {
            text: 'much',
            italic: true,
          },
          {
            text: ' better than a ',
          },
          {
            text: '<textarea>',
            code: true,
          },
          {
            text: '!',
          },
        ],
      },
    ];
    const tree = slateToTemplate(slate);
    expect(tree).toMatchInlineSnapshot(`
      [
        "<p>This is editable <strong>rich</strong> text, <i>much</i> better than a <code>&lt;textarea&gt;</code>!</p>",
      ]
    `);
  });

  test('render Slate node as p tag if defaultTag is set', async () => {
    const slate = [
      {
        children: [
          {
            text: 'Paragraph',
          },
        ],
      },
    ];

    const config = {
      ...defaultTemplateConfig,
      defaultTag: 'p',
    };

    const tree = slateToTemplate(slate, config);
    expect(tree).toMatchInlineSnapshot(`
      [
        "<p>Paragraph</p>",
      ]
    `);
  });

  test('respects a function passed as an element transform', async () => {
    const slate = [
      {
        children: [
          {
            text: 'Paragraph',
          },
        ],
        type: 'p',
      },
      {
        children: [
          {
            buttonType: 'primary',
            text: 'Button',
          },
        ],
        type: 'button',
      },
    ];

    const config: SlateToTemplateConfig = {
      ...defaultTemplateConfig,
      customElementSerializers: {
        button: ({ node }) => {
          return () =>
            `<button class="${node.buttonType}">Button HTML string generated by function</button>`;
        },
      },
    };

    const tree = slateToTemplate(slate, config);
    expect(tree).toMatchInlineSnapshot(`
      [
        "<p>Paragraph</p>",
        [Function],
      ]
    `);
  });

  it('returns undefined when node is not an array', () => {
    expect(slateToTemplate(null as unknown as any[])).toBeUndefined();
  });

  it('uses payloadSlateToTemplateConfig for upload nodes', () => {
    const slate = [
      {
        type: 'upload',
        value: {
          mimeType: 'image/png',
          url: 'https://example.com/a.png',
        },
        children: [{ text: '' }],
      },
    ];
    const tree = slateToTemplate(slate, payloadSlateToTemplateConfig);
    expect(tree?.[0]).toContain('img');
    expect(tree?.[0]).toContain('https://example.com/a.png');
  });

  it('renders the code mark as inline code', () => {
    const slate = [
      {
        type: 'p',
        children: [{ text: 'Use ' }, { text: 'npm', code: true }, { text: ' here.' }],
      },
    ]
    expect(slateToTemplate(slate)).toEqual(['<p>Use <code>npm</code> here.</p>'])
    expect(slateToTemplate(slate, payloadSlateToTemplateConfig)).toEqual(['<p>Use <code>npm</code> here.</p>'])
  })

  it('combines the code mark with other marks', () => {
    const slate = [
      {
        type: 'p',
        children: [{ text: 'Use ' }, { text: 'npm', bold: true, code: true }, { text: ' here.' }],
      },
    ]
    expect(slateToTemplate(slate)).toEqual(['<p>Use <strong><code>npm</code></strong> here.</p>'])
  })

  it('still wraps a code-block element in pre and code', () => {
    const slate = [
      {
        type: 'code-block',
        children: [{ text: 'const a = 1' }],
      },
    ]
    const config: SlateToTemplateConfig = {
      ...defaultTemplateConfig,
      elementTransforms: {
        ...defaultTemplateConfig.elementTransforms,
        'code-block': ({ children = [] }: { children?: ChildNode[] }) =>
          new Element('pre', {}, [new Element('code', {}, children)]),
      },
    }
    expect(slateToTemplate(slate, config)).toEqual(['<pre><code>const a = 1</code></pre>'])
  })

  it('invokes customElementSerializers and returns their values', () => {
    const config: SlateToTemplateConfig = {
      ...defaultTemplateConfig,
      customElementSerializers: {
        callout: ({ node }) => `CALLOUT:${node.children?.[0]?.text}`,
      },
    };
    const slate = [
      {
        type: 'callout',
        children: [{ text: 'Hello' }],
      },
      {
        type: 'p',
        children: [{ text: 'Body' }],
      },
    ];
    expect(slateToTemplate(slate, config)).toEqual(['CALLOUT:Hello', '<p>Body</p>']);
  });
});
