import { Config } from './types'

export const config: Config = {
  elementMap: {
    p: 'paragraph',
    paragraph: 'paragraph',
    h1: 'h1',
    h2: 'h2',
    h3: 'h3',
    h4: 'h4',
    h5: 'h5',
    h6: 'h6',
    ['heading-one']: 'h1',
    ['heading-two']: 'h2',
    ['heading-three']: 'h3',
    ['heading-four']: 'h4',
    ['heading-five']: 'h5',
    ['heading-six']: 'h6',
    blockquote: 'blockquote',
    quote: 'blockquote',
    ['block-quote']: 'blockquote',
    ul: 'ul',
    ['bulleted-list']: 'ul',
    ol: 'ol',
    ['numbered-list']: 'ol',
    li: 'li',
    ['list-item']: 'li',
    ['check-list-item']: 'task',
    link: 'link',
    image: 'image',
    img: 'image',
    br: 'line-break',
    hr: 'hr',
    ['code-block']: 'code-block',
    table: 'table',
    thead: 'table-section',
    tbody: 'table-section',
    tfoot: 'table-section',
    tr: 'table-row',
    ['table-row']: 'table-row',
    th: 'table-cell',
    td: 'table-cell',
    ['table-header-cell']: 'table-cell',
    ['table-cell']: 'table-cell',
  },
  markMap: {
    bold: 'strong',
    italic: 'emphasis',
    strikethrough: 'strikethrough',
    underline: { open: '<u>', close: '</u>' },
    subscript: { open: '<sub>', close: '</sub>' },
    superscript: { open: '<sup>', close: '</sup>' },
    code: 'code',
  },
  elementTransforms: {},
  emphasisDelimiter: '*',
  bulletMarker: '-',
  escape: true,
}
